class Config {

    static applicationId = 'com.mny.mojito'
    static appName = 'Mojito'

    static compileSdkVersion = 30
    static minSdkVersion = 21
    static targetSdkVersion = 30
    static versionCode = 1_000_000
    static buildToolsVersion = '31.0.0'
    static versionName = '1.0.0'// E.g. 1.9.72 => 1,009,072
    static buglyId = '2ad34b4d35'// E.g. 1.9.72 => 1,009,072

    static gradlePluginVersion = '4.2.2'
    static kotlinVersion = '1.5.21'
    static nav_version = "2.3.5"
    static room_version = "2.3.0"
    static hiltVersion = "2.40"

    static version = "2.0.3"
    static fragment_version = "1.3.6"
    static lifecycle_version = "2.4.0-alpha03"
    static paging_version = "3.0.1"
    static glide_version = "4.12.0"
    static coroutineVersion = "1.5.2"
    static retrofit_version = "2.9.0"
    static dokit_version = "3.5.0.1"
    static immersionBarVersion = "3.0.0"


    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_mock               : new DepConfig(false, true , ":feature:mock"),
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_eyepetizer_app     : new DepConfig(false, true , ":feature:eyepetizer:app"),
            feature_eyepetizer_pkg     : new DepConfig(true , true , ":feature:eyepetizer:pkg", "com.mny.mojito:feature_eyepetizer_pkg:latest.integration"),
            feature_eyepetizer_export  : new DepConfig(true , true , ":feature:eyepetizer:export", "com.mny.mojito:feature_eyepetizer_export:latest.integration"),
            feature_flow_app           : new DepConfig(false, true , ":feature:flow:app"),
            feature_flow_pkg           : new DepConfig(false, true , ":feature:flow:pkg", "com.mny.mojito:feature_flow_pkg:latest.integration"),
            feature_flow_export        : new DepConfig(false, true , ":feature:flow:export", "com.mny.mojito:feature_flow_export:latest.integration"),
            feature_widget_app         : new DepConfig(true , true , ":feature:widget:app"),
            feature_widget_pkg         : new DepConfig(true , true , ":feature:widget:pkg", "com.mny.mojito:feature_widget_pkg:latest.integration"),
            feature_widget_export      : new DepConfig(true , true , ":feature:widget:export", "com.mny.mojito:feature_widget_export:latest.integration"),
            feature_user_app           : new DepConfig(false, true , ":feature:user:app"),
            feature_user_pkg           : new DepConfig(true , true , ":feature:user:pkg", "com.mny.mojito:feature_user_pkg:latest.integration"),
            feature_user_export        : new DepConfig(true , true , ":feature:user:export", "com.mny.mojito:feature_user_export:latest.integration"),
            feature_wan_app            : new DepConfig(false, true , ":feature:wan:app"),
            feature_wan_pkg            : new DepConfig(true , true , ":feature:wan:pkg", "com.mny.mojito:feature_wan_pkg:latest.integration"),
            feature_wan_export         : new DepConfig(true , true , ":feature:wan:export", "com.mny.mojito:feature_wan_export:latest.integration"),
            lib_base                   : new DepConfig(true , true , ":lib:base", "com.mny.mojito:lib_base:latest.integration"),
            lib_common                 : new DepConfig(true , true , ":lib:common", "com.mny.mojito:lib_common:latest.integration"),
            lib_lang                   : new DepConfig(true , true , ":lib:lang", "com.mny.mojito:lib_lang:latest.integration"),
            lib_widget                 : new DepConfig(true , true , ":lib:widget", "com.mny.mojito:lib_widget:latest.integration"),
            lib_mojito                 : new DepConfig(true , true , ":lib:mojito", "com.mny.mojito:lib_mojito:latest.integration"),
            /*Never delete this line*/
//            feature_template_app       : new DepConfig(":feature:template:app"),
//            feature_template_pkg       : new DepConfig(":feature:template:pkg"),
//            feature_template_export    : new DepConfig(":feature:template:export"),
            plugin_gradle            : new DepConfig(pluginPath: "com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_kotlin            : new DepConfig(pluginPath: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),
            plugin_hilt              : new DepConfig(pluginPath: "com.google.dagger:hilt-android-gradle-plugin:$hiltVersion", pluginId: "dagger.hilt.android.plugin"),
            plugin_api               : new DepConfig(pluginPath: "com.blankj:api-gradle-plugin:1.5", pluginId: "com.blankj.api"),
            plugin_bus               : new DepConfig(pluginPath: "com.blankj:bus-gradle-plugin:2.6", pluginId: "com.blankj.bus"),
            plugin_navigation        : new DepConfig(pluginPath: "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version",pluginId: "androidx.navigation.safeargs.kotlin"),
            plugin_version_check     : new DepConfig(pluginPath: "com.github.ben-manes:gradle-versions-plugin:0.38.0"),
            plugin_dokit             : new DepConfig(pluginPath: "io.github.didi.dokit:dokitx-plugin:$dokit_version", pluginId: "com.didi.dokit"),
            plugin_maven             : new DepConfig(pluginPath: "com.github.dcendents:android-maven-gradle-plugin:2.1", pluginId: "com.github.dcendents.android-maven"),// 上传到 maven
            plugin_bintray           : new DepConfig(pluginPath: "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4", pluginId: "com.jfrog.bintray"),// 上传到 bintray

            kotlin                   : new DepConfig("org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"),
            utilcode                 : new DepConfig("com.blankj:utilcode:1.30.6"),
            free_proguard            : new DepConfig("com.blankj:free-proguard:1.0.2"),
            swipe_panel              : new DepConfig("com.blankj:swipe-panel:1.2"),

            leakcanary_android       : new DepConfig("com.squareup.leakcanary:leakcanary-android:2.7"),
            arouter                  : new DepConfig("com.alibaba:arouter-api:1.3.1"),
            compiler                 : new DepConfig("com.alibaba:arouter-compiler:1.1.4"),
            kotlinReflect            : new DepConfig("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"),
            kotlinAndroidExtensions  : new DepConfig(false, "org.jetbrains.kotlin:kotlin-android-extensions:$kotlinVersion"),
            coroutinesAndroid        : new DepConfig("org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutineVersion"),
            coroutinesCore           : new DepConfig("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion"),
            coil                     : new DepConfig("io.coil-kt:coil:1.4.0"),

            appcompat                : new DepConfig("androidx.appcompat:appcompat:1.3.1"),
            recyclerView             : new DepConfig("androidx.recyclerview:recyclerview:1.2.1"),
            coreKtx                  : new DepConfig("androidx.core:core-ktx:1.6.0"),
            activityKtx              : new DepConfig("androidx.activity:activity-ktx:1.2.0-alpha04"),
            constraintlayout         : new DepConfig("androidx.constraintlayout:constraintlayout:2.1.1"),
            cardview                 : new DepConfig("androidx.cardview:cardview:1.0.0"),
            multidex                 : new DepConfig("androidx.multidex:multidex:2.0.1"),
            legacy                   : new DepConfig("androidx.legacy:legacy-support-v4:1.0.0"),
            viewpager                : new DepConfig("androidx.viewpager:viewpager:1.0.0"),
            viewpager2               : new DepConfig("androidx.viewpager2:viewpager2:1.0.0"),
            // Fragment
            fragment                 : new DepConfig("androidx.fragment:fragment:$fragment_version"),
            fragmentKtx              : new DepConfig("androidx.fragment:fragment-ktx:$fragment_version"),
            fragmentTesting          : new DepConfig("androidx.fragment:fragment-testing:$fragment_version"),
            // Lifecycle
            lifecycleRuntime         : new DepConfig("androidx.lifecycle:lifecycle-runtime:$lifecycle_version"),
            lifecycleRuntimeKtx      : new DepConfig("androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"),
            lifecycleCompiler        : new DepConfig("androidx.lifecycle:lifecycle-compiler:$lifecycle_version"),
            lifecycleProcess         : new DepConfig("androidx.lifecycle:lifecycle-process:$lifecycle_version"),
            lifecycleVM              : new DepConfig("androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"),
            lifecycleVMKtx           : new DepConfig("androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"),
            lifecycleLiveData        : new DepConfig("androidx.lifecycle:lifecycle-livedata:$lifecycle_version"),
            lifecycleLiveDataKtx     : new DepConfig("androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"),
            lifecycleVMKSavedState   : new DepConfig("androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"),
            commonJava8              : new DepConfig("androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"),
            service                  : new DepConfig("androidx.lifecycle:lifecycle-service:$lifecycle_version"),
            // Navigation
            navigation_runtime       : new DepConfig("androidx.navigation:navigation-runtime:$nav_version"),
            navigation_fragment      : new DepConfig("androidx.navigation:navigation-fragment:$nav_version"),
            navigation_fragmentKtx   : new DepConfig("androidx.navigation:navigation-fragment-ktx:$nav_version"),
            navigation_ui            : new DepConfig("androidx.navigation:navigation-ui:$nav_version"),
            navigation_uiKtx         : new DepConfig("androidx.navigation:navigation-ui-ktx:$nav_version"),
            navigation_dynamic       : new DepConfig("androidx.navigation:navigation-dynamic-features-fragment:$nav_version"),
            navigation_testing       : new DepConfig("androidx.navigation:navigation-testing:$nav_version"),
            // Room
            roomRuntime              : new DepConfig("androidx.room:room-runtime:$room_version"),
            roomCompiler             : new DepConfig("androidx.room:room-compiler:$room_version"),
            roomKtx                  : new DepConfig("androidx.room:room-ktx:$room_version"),
            roomGuava                : new DepConfig("androidx.room:room-guava:$room_version"),
            roomTesting              : new DepConfig("androidx.room:room-testing:$room_version"),

            // Paging
            pagingRuntime            : new DepConfig("androidx.paging:paging-runtime:$paging_version"),
            pagingRuntimeKtx         : new DepConfig("androidx.paging:paging-runtime-ktx:$paging_version"),
            pagingTestingCommon      : new DepConfig("androidx.paging:paging-common:$paging_version"),
            pagingTestingCommonKtx   : new DepConfig("androidx.paging:paging-common-ktx:$paging_version"),
            // Test
            jUnit                    : new DepConfig("junit:junit:4.13.2"),
            androidJunit             : new DepConfig("androidx.test.ext:junit:1.1.2"),
            androidJUnitRunner       : new DepConfig("androidx.test.runner.AndroidJUnitRunner"),
            androidRunner            : new DepConfig("androidx.test:runner:1.3.0"),
            espresso                 : new DepConfig("androidx.test.espresso:espresso-core:3.3.0"),

            materialiconlib          : new DepConfig("net.steamcrafted:materialiconlib:1.1.5"),
            mmkv                     : new DepConfig("com.tencent:mmkv-static:1.2.11"),

            hilt                     : new DepConfig("com.google.dagger:hilt-android:$hiltVersion"),
            hiltCompiler             : new DepConfig("com.google.dagger:hilt-android-compiler:$hiltVersion"),

            material                 : new DepConfig("com.google.android.material:material:1.4.0"),
            gson                     : new DepConfig("com.google.code.gson:gson:2.8.9"),

            glide                    : new DepConfig("com.github.bumptech.glide:glide:$glide_version"),
            glide_compiler           : new DepConfig("com.github.bumptech.glide:compiler:$glide_version"),

            retrofit                 : new DepConfig("com.squareup.retrofit2:retrofit:${retrofit_version}"),
            gsonConverter            : new DepConfig("com.squareup.retrofit2:converter-gson:${retrofit_version}"),
            okHttp4                  : new DepConfig("com.squareup.okhttp3:okhttp:4.9.2"),

            androideventbus          : new DepConfig("org.simple:androideventbus:1.0.5.1"),
            eventbus                 : new DepConfig("org.greenrobot:eventbus:3.1.1"),

            // Refresh
            swiperefreshlayout       : new DepConfig("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"),   //���ı�������
            refresh_core             : new DepConfig("com.scwang.smart:refresh-layout-kernel:$version"),   //���ı�������
            refresh_headerClassics   : new DepConfig("com.scwang.smart:refresh-header-classics:$version"), //����ˢ��ͷ
            refresh_headerRadar      : new DepConfig("com.scwang.smart:refresh-header-radar:$version"),   //�״�ˢ��ͷ
            refresh_headerFalsify    : new DepConfig("com.scwang.smart:refresh-header-falsify:$version"),   //����ˢ��ͷ
            refresh_headerMaterial   : new DepConfig("com.scwang.smart:refresh-header-material:$version"),  //�ȸ�ˢ��ͷ
            refresh_headerTwoLevel   : new DepConfig("com.scwang.smart:refresh-header-two-level:$version"), //����ˢ��ͷ
            refresh_footerBall       : new DepConfig("com.scwang.smart:refresh-footer-ball:$version"),   //���������
            refresh_footerClassics   : new DepConfig("com.scwang.smart:refresh-footer-classics:$version"),   //�������

//            qmui                   : new DepConfig("com.qmuiteam:qmui:2.0.0-alpha10"),

            banner                   : new DepConfig("com.youth.banner:banner:2.1.0"),
            datastore                : new DepConfig("androidx.datastore:datastore:1.0.0-alpha03"),
            flexbox                  : new DepConfig("com.google.android:flexbox:2.0.1"),
            brvah                    : new DepConfig("com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.6"),
            liveEventBus             : new DepConfig("com.jeremyliao:live-event-bus-x:1.7.3"),
            lottie                   : new DepConfig("com.airbnb.android:lottie:4.2.0"),
            dokit                    : new DepConfig(false, "io.github.didi.dokit:dokitx:$dokit_version"),
            dokitNoOp                : new DepConfig(false, "io.github.didi.dokit:dokitx-no-op:$dokit_version"),
            anchors                  : new DepConfig("com.github.YummyLau:Anchors:v1.1.4"),
            unpeek_livedata          : new DepConfig("com.kunminx.arch:unpeek-livedata:6.0.0-beta1"),
            immersionBarCore         : new DepConfig("com.gyf.immersionbar:immersionbar:$immersionBarVersion"),
            immersionBarComponents   : new DepConfig("com.gyf.immersionbar:immersionbar-components:$immersionBarVersion"),
            immersionBarKtx          : new DepConfig("com.gyf.immersionbar:immersionbar-ktx:$immersionBarVersion"),
            bugly                    : new DepConfig("com.tencent.bugly:crashreport:3.4.4"),
            buglyNative              : new DepConfig("com.tencent.bugly:nativecrashreport:3.9.2"),
            x5WebView                : new DepConfig("com.tencent.tbs.tbssdk:sdk:43993"),
            preference               : new DepConfig("androidx.preference:preference-ktx:1.1.1"),
            rvDivider                : new DepConfig("com.github.fondesa:recycler-view-divider:3.5.0"),
            xPopup                   : new DepConfig("com.github.li-xiaojun:XPopup:2.6.6"),
    ]
}